### ISSUE TITLE
Orientation is an empty object on iOS16

### ISSUE THREAD

**Issue by gee1k** [apache/cordova-plugin-screen-orientation#114]
# Bug Report

## Problem

Orientation is empty on iOS 16, the same code works fine on my old device (ios 14)

### Environment, Platform, Device

iPhone 12: iOS 16.3.1
iPad mini6: 16.3.1

### Version information
Cordova CLI: 11.1.0
Cordova Platforms: cordova-ios 6.2.0
cordova-plugin-screen-orientation: 3.0.3
Ionic Framework: 3.9.10

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by thoasty-dev** [comment]
Can confirm, ie `unlock is not a function` on window.screen.orientation anymore

**Comment by diesieben07** [comment]
As a workaround I am using `window.cordova.plugins.screenorientation.setOrientation` for now.
I suspect this is caused by Safari now supporting the screen orientation API (`screen.orientation`). In my tests it seems like some kind of race condition between this plugin and Safari itself setting `screen.orientation`, because _sometimes_ it does work (especially if you add log statements logging out the value of `screen.orientation`).

**Comment by 9t96** [comment]
@diesieben07 Solution worked for me. But I think theres not a way to setOrientation for both landscape-primary and landscape-secodary allowing the device to automatically rotate to primary or secondary position. Isn't it? Im testing on Ipad Pro 3gen IOS 16.4

**Comment by paulovargatt** [comment]
its works for me

if (window.screen.orientation.lock) {
      window.screen.orientation.lock('portrait');
    } else if (window['cordova'] && window['cordova'].plugins && window['cordova'].plugins.screenorientation) {
      window['cordova'].plugins.screenorientation.setOrientation('portrait');
    }

**Comment by DeveloperHitesh** [comment]
Facing issue while trying to open camera in application.

ERROR: Unhandled Promise rejection: plugin_not_installed ; Zone: <root> ; Task: Promise.then ; Value: plugin_not_installed
WARN: Native: tried calling ScreenOrientation.lock, but the ScreenOrientation plugin is not installed.
WARN: Install the ScreenOrientation plugin: 'ionic cordova plugin add cordova-plugin-screen-orientation'
ERROR: Unhandled Promise rejection: plugin_not_installed ; Zone: <root> ; Task: Promise.then ; Value: plugin_not_installed
WARN: Native: tried calling ScreenOrientation.lock, but the ScreenOrientation plugin is not installed.
WARN: Install the ScreenOrientation plugin: 'ionic cordova plugin add cordova-plugin-screen-orientation'
ERROR: Unhandled Promise rejection: plugin_not_installed ; Zone: <root> ; Task: Promise.then ; Value: plugin_not_installed

This issue is occure after getting update of ios version 16.4 and 16.5, on lower version i'm able to access camera easily.

Below plugin used for 

"cordova-ios": "^6.3.0",
"@ionic-native/camera-preview": "^5.27.0",
"cordova-plugin-camera-preview": "^0.12.3",
"cordova-plugin-screen-orientation": "^3.0.2"

Reference link for similar issue : https://github.com/ionic-team/capacitor/issues/6459

Implemented this change on local but not working : https://github.com/apache/cordova-plugin-screen-orientation/pull/116/commits/f8479d5c7bc938edf782bf4ebcedc0cfa8ceb7e8

Can you help me on this any pointers on same it will help full for me.

Thanks in advance.

**Comment by NathanPepperoni** [comment]
Just to keep it alive, we are currently blocked on updating our iOS build nodes by this issue. Unfortunately the proposed workarounds dont work in our position without significant refactor, as a lot of legacy code depends on specifically `window.screen.orientation.lock`
