### ISSUE TITLE
screen.orientation.lock() is not available on this device.

### ISSUE THREAD

**Issue by Lahrachtdi** [apache/cordova-plugin-screen-orientation#35]
Getting this error: screen.orientation.lock() is not available on this device.
Config: 
- android platfrom: 7.1.1
- cordova-plugin-screen-orientation: ^3.0.1
- Device android version: 6.0.1
- Device name: Sumsung Grand Prime Pus

**Comment by janpio** [comment]
In general I would say: Seems the plugin thinks this functionality is not supported on that device.

Can you give some more context on the error?
What line is causing it etc.?
Then we can find the code throwing it and understand what is going on.

**Comment by neverender24** [comment]
when using IonicDevApp, I  encounter this same error.

Although there are instances that it will work.

Android 8.0.0

Samsung s8.

**Comment by muhammadomais** [comment]
I am getting the same error. Is this issue fixed?
Android Version 9
Samsung S9+

**Comment by tianma3798** [comment]
我这华为荣耀8
Android 8.0.0
也遇到同样的错误了

**Comment by timbru31** [comment]
@tianma3798, please stick to English.
Roughly translated your message means:

> I am Huawei glory 8
Android 8.0.0
I also encountered the same error.
Carefully check that you have forgotten to install the module, cordova plugin add cordova-plugin-screen-orientation

**Comment by breautek** [comment]
From what I can gather, it appears that chrome has never supported `screen.orientation.lock`, but at some point they added the function, that raises an exception when used. (Maybe it's only supported on specific devices?)

https://github.com/apache/cordova-plugin-screen-orientation/blob/3c08d393ffe0df5fa16f7fcbab06c22648dcc3ed/www/screenorientation.js#L57-L59

These lines above checks for existing of the native api and uses it if available, then it looks like it falls back to a custom solution if not. I haven't tested this, but perhaps we can force use the fallback.

The issue was raised back in 2017, but remained unresolved and archived (with no attached reason) in 2018.

**Comment by mayankkataria** [comment]
Still facing this issue. Did anybody found a solution?

**Comment by qiutian00** [comment]
can not solve the problem

**Comment by qiutian00** [comment]
@mayankkataria  , i find the solve method, add <preference name="Orientation" value="landscape" /> in [config.xml](https://cordova.apache.org/docs/en/3.1.0/config_ref/) ， like this: [![6ATOS0.png](https://s4.ax1x.com/2021/03/03/6ATOS0.png)](https://imgtu.com/i/6ATOS0)

**Comment by snsxn** [comment]
After some research, my App in Android works using preference orientation sensorPortrat inside android platform tags.
Screen orientation plugin is not working
